name: CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test: # Test 이름
    runs-on: ubuntu-latest # 최신 우분투 환경에서 실행

    steps: # 어떤 작업을 순서대로 실행할지 정의
    - name: Checkout repository 
      uses: actions/checkout@v3 # uses: actions/checkout@v3는 GitHub Actions에서 제공하는 액션으로, 리포지토리를 체크아웃하는 데 사용됩니다.

    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.10

    - name: Install dependencies 
      run: |
        pip install -r requirements.txt

    - name: Run tests 
      run: | 
        pytest -v -s 
      # pytest는 Python의 테스트 프레임워크로, -v는 verbose 모드로 실행하여 더 많은 정보를 출력하고, -s는 print 문을 사용하여 출력된 내용을 보여줍니다.
    - name: Deploy via Webhook
      if: success()
      run: |
        curl -X POST http://127.0.0.1:6001/hook 
      # webhook을 통해 배포를 트리거하는 curl 명령어입니다.