name: Build Docker Image

on:
  workflow_run:
    workflows: ["CI Test"] # CI Test 워크플로우가 성공적으로 완료된 후에 이 워크플로우가 실행됩니다.
    types:
      - completed # CI Test 워크플로우가 완료된 후에 이 워크플로우가 실행됩니다.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 # 이 action은 Docker Buildx를 설정하는 데 사용됩니다. Buildx는 Docker의 빌드 도구로, 멀티 플랫폼 빌드를 지원합니다.

    - name: Login to DockerHub 
      uses: docker/login-action@v2 # 이 action은 DockerHub에 로그인하는 데 사용됩니다. DockerHub는 Docker 이미지를 저장하고 공유하는 플랫폼입니다.
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-cicd-app:latest
    - name: Deploy via Webhook
      if: success()
      run: |
          curl -X POST https://7072-211-196-103-173.ngrok-free.app/hook
        # webhook을 통해 배포를 트리거하는 curl 명령어입니다. a
        
